import Head from "next/head";
import { Inter } from "next/font/google";
import Link from "next/link";
import { StyledContainer, StyledLoginContainer } from "./login";
import { Button } from "@mui/material";
import { toast } from "react-toastify";
const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <StyledContainer style={{ height: "100vh" }}>
      
        <Link href="/login">
          <Button>
            <StyledLoginContainer>
              <h1>Welcome To Check</h1>
              Go
            </StyledLoginContainer>
          </Button>
        </Link>
      </StyledContainer>
    </>
  );
}
